# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/CA_Labs/Lab2/spi_memory/spi_memory.cache/wt [current_project]
set_property parent.project_path C:/CA_Labs/Lab2/spi_memory/spi_memory.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths c:/CA_Labs/Lab2/spi_memory/spi_memory.srcs/sources_1/imports/Lab2 [current_project]
read_verilog -library xil_defaultlib {
  C:/CA_Labs/Lab2/spi_memory/spi_memory.srcs/sources_1/imports/Lab2/shiftregister.v
  C:/CA_Labs/Lab2/spi_memory/spi_memory.srcs/sources_1/imports/Lab2/inputconditioner.v
  C:/CA_Labs/Lab2/spi_memory/spi_memory.srcs/sources_1/imports/Lab2/datamemory.v
  C:/CA_Labs/Lab2/spi_memory/spi_memory.srcs/sources_1/imports/Lab2/fsm.v
  C:/CA_Labs/Lab2/spi_memory/spi_memory.srcs/sources_1/imports/Lab2/spimemory.v
}
synth_design -top spiMemory -part xc7z010clg400-1
write_checkpoint -noxdef spiMemory.dcp
catch { report_utilization -file spiMemory_utilization_synth.rpt -pb spiMemory_utilization_synth.pb }
