# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/CA_Labs/Lab2/midpoint_deliverable/midpoint_deliverable.cache/wt [current_project]
set_property parent.project_path C:/CA_Labs/Lab2/midpoint_deliverable/midpoint_deliverable.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  C:/CA_Labs/Lab2/inputconditioner.v
  C:/CA_Labs/Lab2/midpoint.v
  C:/CA_Labs/Lab2/midpoint_deliverable/midpoint_deliverable.srcs/sources_1/new/fpga_wrapper.v
}
read_xdc {{C:/Users/reggert/Box Sync/Olin/Year IV/CompArch/support/ZYBO_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/reggert/Box Sync/Olin/Year IV/CompArch/support/ZYBO_Master.xdc}}]

synth_design -top lab2_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef lab2_wrapper.dcp
catch { report_utilization -file lab2_wrapper_utilization_synth.rpt -pb lab2_wrapper_utilization_synth.pb }
